# Generated by Django 3.1.3 on 2023-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201222_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='companies',
            field=models.TextField(default='aa'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.TextField(default='dd'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.FloatField(default=11),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
